# Generated by Django 6.0.4 on 2026-04-24 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('landing_lat', models.FloatField()),
                ('landing_lng', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('ready', 'Ready for Drone'), ('loaded', 'Loaded into Drone'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Location'), ('delivering', 'Lowering Food'), ('delivered', 'Delivered Successfully'), ('stuck', 'Package Stuck'), ('failed', 'Delivery Failed')], default='pending', max_length=20)),
                ('transit_phase', models.CharField(blank=True, choices=[('', 'None'), ('to_restaurant', 'To Restaurant'), ('to_customer', 'To Customer'), ('to_charging', 'To Charging Station'), ('to_charging_from_restaurant', 'To Charging Station (Resume Restaurant)'), ('to_charging_from_customer', 'To Charging Station (Resume Customer)')], default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
            ],
        ),
    ]
