# Generated by Django 6.0.4 on 2026-04-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transit_phase',
            field=models.CharField(blank=True, choices=[('', 'None'), ('to_restaurant', 'To Restaurant'), ('to_customer', 'To Customer'), ('to_charging', 'To Charging Station'), ('to_charging_from_restaurant', 'To Charging Station'), ('to_charging_from_customer', 'To Charging Station')], default='', max_length=40),
        ),
    ]
